<template>
  <section class="folder-page">
    <div class="page-header"><h2>文件夹</h2><div class="header-actions"><button class="btn-new" @click="showCreate=true">+ 新建文件夹</button><router-link to="/" class="back-link">← 返回转换</router-link></div></div>
    <p v-if="store.error" class="msg-error">{{ store.error }}</p>
    <div v-if="showCreate" class="modal-overlay" @click.self="showCreate=false"><div class="mini-modal"><h3>新建文件夹</h3><input v-model="newName" class="field" placeholder="文件夹名称" @keyup.enter="doCreate" maxlength="64" /><div class="actions"><button class="btn-cancel" @click="showCreate=false">取消</button><button class="btn-apply" @click="doCreate">创建</button></div></div></div>
    <div v-if="showRename" class="modal-overlay" @click.self="showRename=false"><div class="mini-modal"><h3>重命名</h3><input v-model="renameName" class="field" placeholder="新名称" @keyup.enter="doRename" maxlength="64" /><div class="actions"><button class="btn-cancel" @click="showRename=false">取消</button><button class="btn-apply" @click="doRename">确认</button></div></div></div>
    <div v-if="store.loading" class="msg-loading">加载中…</div>
    <div v-else-if="!store.folders.length" class="msg-empty">暂无文件夹</div>
    <div v-else class="folder-grid"><div v-for="f in store.folders" :key="f.id" class="folder-card" :class="{active:activeFolder===f.id}" @click="openFolder(f)"><div class="folder-info"><span class="folder-icon">📁</span><span class="folder-name">{{ f.name }}</span></div><div class="folder-actions"><button class="btn-sm" @click.stop="startRename(f)">✏️</button></div></div></div>
    <div v-if="activeFolder" class="records-section"><h3>{{ activeFolderName }} — 剧本列表</h3><p v-if="recordsLoading" class="msg-loading">加载中…</p>
      <table v-else-if="folderRecords.length" class="history-table"><thead><tr><th>小说预览</th><th>风格</th><th>时间</th><th>操作</th></tr></thead><tbody><tr v-for="r in folderRecords" :key="r.id"><td class="col-preview">{{ r.novel_preview }}{{ r.novel_preview.length>=100?'…':'' }}</td><td>{{ styleLabel(r.style) }}</td><td>{{ formatTime(r.created_at) }}</td><td><router-link :to="`/history/${r.id}?from=folders`" class="btn-view">查看</router-link></td></tr></tbody></table>
      <p v-else class="msg-empty">此文件夹暂无剧本</p></div>
  </section>
</template>
<script setup>
import { ref, onMounted } from 'vue'; import api from '../api'; import { useFolderStore } from '../stores/folder'
const store=useFolderStore(); const showCreate=ref(false); const newName=ref(''); const showRename=ref(false); const renameName=ref(''); const renameId=ref(null)
const activeFolder=ref(null); const activeFolderName=ref(''); const folderRecords=ref([]); const recordsLoading=ref(false)
onMounted(()=>store.fetchFolders())
async function doCreate(){if(!newName.value.trim())return;await store.createFolder(newName.value.trim());newName.value='';showCreate.value=false}
function startRename(f){renameId.value=f.id;renameName.value=f.name;showRename.value=true}
async function doRename(){if(!renameName.value.trim())return;await store.renameFolder(renameId.value,renameName.value.trim());showRename.value=false}
async function openFolder(f){activeFolder.value=f.id;activeFolderName.value=f.name;recordsLoading.value=true;try{const r=await api.get(`/folders/${f.id}/records`);folderRecords.value=r.data}catch{}finally{recordsLoading.value=false}}
function styleLabel(s){return{faithful_realism:'原著忠实写实',fast_paced:'强爽点',slice_of_life:'市井烟火',documentary:'纪实',family_friendly:'合家欢',crime_thriller:'悬疑刑侦',poetic_minimalist:'意象留白',lyrical_prose:'抒情散文诗',absurdist_arthouse:'荒诞文艺',epic_fantasy:'史诗宏大',light_fantasy:'轻量化魔改',soft_scifi:'软科幻',honkaku_mystery:'本格推理',horror_atmosphere:'惊悚氛围',social_suspense:'社会派悬疑',slapstick_absurd:'无厘头',light_comedy:'轻喜剧',satirical_dark:'黑色喜剧'}[s]??s}
function formatTime(iso){return iso?iso.replace('T',' ').slice(0,19):''}
</script>
<style scoped>
.folder-page{max-width:900px;margin:0 auto}.page-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:1.25rem}.page-header h2{font-size:1.25rem;color:var(--text-primary)}.header-actions{display:flex;gap:.75rem;align-items:center}.back-link{font-size:.9rem;color:var(--accent);text-decoration:none}.btn-new{padding:.4rem 1rem;font-size:.85rem;color:var(--btn-primary-text);background:var(--accent);border:none;border-radius:6px;cursor:pointer}.msg-error{color:var(--danger)}.msg-loading{color:var(--text-secondary);text-align:center;padding:2rem}.msg-empty{color:var(--text-muted);text-align:center;padding:2rem}.folder-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:.75rem;margin-bottom:2rem}.folder-card{background:var(--bg-card);border-radius:8px;padding:1rem;cursor:pointer;box-shadow:0 1px 3px var(--shadow);display:flex;justify-content:space-between;align-items:center;border:2px solid transparent}.folder-card.active{border-color:var(--accent)}.folder-info{display:flex;align-items:center;gap:.5rem}.folder-icon{font-size:1.3rem}.folder-name{font-size:.9rem;color:var(--text-primary)}.btn-sm{padding:.15rem .4rem;font-size:.8rem;border:none;background:transparent;cursor:pointer}.records-section{margin-top:1rem}.records-section h3{font-size:1rem;color:var(--text-primary);margin-bottom:.75rem}.history-table{width:100%;border-collapse:collapse;background:var(--bg-card);border-radius:8px;overflow:hidden;box-shadow:0 1px 3px var(--shadow)}.history-table th{background:var(--bg-card-alt);color:var(--text-secondary);font-weight:600;font-size:.8rem;padding:.75rem 1rem;text-align:left;border-bottom:1px solid var(--border-light)}.history-table td{padding:.75rem 1rem;font-size:.9rem;color:var(--text-primary);border-bottom:1px solid var(--border-light)}.col-preview{max-width:300px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.btn-view{padding:.25rem .7rem;font-size:.8rem;color:var(--accent);background:var(--accent-light);border-radius:4px;text-decoration:none}.modal-overlay{position:fixed;inset:0;background:rgba(0,0,0,.4);display:flex;justify-content:center;align-items:center;z-index:100}.mini-modal{background:var(--bg-card);border-radius:12px;padding:1.5rem;width:90%;max-width:380px;box-shadow:0 8px 32px var(--shadow)}.mini-modal h3{font-size:1.05rem;color:var(--text-primary);margin-bottom:.75rem}.field{width:100%;padding:.5rem .7rem;border:1px solid var(--border);border-radius:6px;font-size:.9rem;background:var(--bg-input);color:var(--text-primary)}.field:focus{outline:none;border-color:var(--accent)}.actions{display:flex;gap:.5rem;justify-content:flex-end;margin-top:.75rem}.btn-cancel{padding:.4rem 1rem;font-size:.85rem;color:var(--text-secondary);background:var(--bg-card-alt);border:1px solid var(--border-light);border-radius:6px;cursor:pointer}.btn-apply{padding:.4rem 1rem;font-size:.85rem;color:var(--btn-primary-text);background:var(--accent);border:none;border-radius:6px;cursor:pointer}
</style>
